### ISSUE TITLE
Champion doesn't have fifth pokemon

### ISSUE THREAD

**Issue by Wofi** [Ishadijcks/Ishadijcks.github.io#11]
The Champion's fifth pokemon (which should vary based off the player's starter) doesn't appear even though it's defined in the code.

**Comment by diff-by-default** [comment]
Looks like the first time you load the game (or reset), the loadTowns() function is getting called before you actually choose a starter. Refreshing the page after you have a starter selected will re-load the array and correctly load the last Champions pokemon.

The code in question can be found [here](https://github.com/Ishadijcks/Ishadijcks.github.io/blob/9d9674d783c072b1c791bd3f61b0b7676e482632/PokeClicker/system.js#L61-L71)

**Comment by Ishadijcks** [comment]
Thank you so much, I totally missed that. I was trying to reproduce but couldn't.

**Comment by Ishadijcks** [comment]
Fixed, towns are now also loaded after a starter is picked.
