### ISSUE TITLE
Optimize Quests

### ISSUE THREAD

**Issue by Dimava** [Ishadijcks/Ishadijcks.github.io#112]
- [x ] Add quests from #69 
- [x] Add Mine quests
- [x] Add Colores Shards quests
- [x] Amount-based reward
- [x] Optimise rewards (moved from #93 )
- [x] Repair quests if they stop working
// Prepare `Story quest` base - coming soon...?
// Allow multiple quests possibility - not coming soon.

**Comment by Ishadijcks** [comment]
Multiple quest possibility is not gonna happen.
