### ISSUE TITLE
Lock features behind 'key items'

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#113]
Right now the player is bombarded with features at the start. I want to add certain key items that need to be unlocked before you can start a feature. In the Pokédex modal there can be a tab with all key items greyed out, with an explanation how to get them.

For example:

Name | Feature | Where to get it
------------ | ------------- | -------------
Shard case | Shards | First prestige
Dungeon pass | Dungeons | Found on route 1
Underground key | Underground | Bought for 10 quest points
Safari ticket | Safari Zone | Fuchsia City gym defeat
Hatchery | Breeding | Pewter city gym defeat
 _Name needed_ | Mom | First level 100 Pokémon
Teachy TV | Oak explain | At the start
_Name needed_ | Garden | First seed drop

Thoughts?
We also need images for each of these items. That might be a problem.

**Comment by Aegyo** [comment]
- Shard Case

Lens Case from R/S/E
http://www.serebii.net/itemdex/sprites/lenscase.png
- Dungeon Pass

I think Dimava added a dungeon tickets image for the fancy item drop animations
- Underground Key

Basement Key from R/S/E
http://www.serebii.net/itemdex/sprites/basementkey.png
- Safari Ticket

Any of the many tickets from R/S/E key items
http://www.serebii.net/itemdex/list/keyitem.shtml
- Hatchery

Not sure for this one, maybe Pokemon GO incubators
- lvl 100 breeding @ mom

Not sure for this one either
- Teachy TV

FR/LG Teachy TV
http://www.serebii.net/red_green/items/teach-tv.gif (I have no idea why this is a gif)
- Garden

Name: Berry Patch
Image: R/S/E wailmer pail
http://www.serebii.net/itemdex/sprites/wailmerpail.png

**Comment by gro-te** [comment]
Breeding at mom.

Mom's letter.
alt text: Your mother has been worrying about you, you never seem to visit anymore.
Image: Any of the letters in the key items list.

**Comment by Ishadijcks** [comment]
Ah good one.
