### ISSUE TITLE
Losing shiny pokemon will prevent people from restarting the game for new updates

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#119]
It is recommended to reset at each major update, but many people probably do not do this because they do not want to lose all of their shiny pokemon.

How about an option to reset, but you start with an array in your savegame listing all of your old shiny pokemon, and when you catch a new pokemon this array is checked.

Alternatively, there could be 2 save slots available to choose from in the save modal. This would let you keep your old save without having to export and keep a file to later import.

Write any other ideas you might have.

**Comment by Dimava** [comment]
- Weak reset
  - keep  shinies **as eggs**, bought and rock-evolved
  - lose all other pokemons
  - +10 money multiplier until new TotalMoney
  - keep shards/shard upgrades/egg slots/undeground
  - items cost /=10 until you buy off before-reset amount
- Temp reset
  - lose everything, get it back in couple of days

https://thepasteb.in/p/NxhrcRDkJo2lAhO

**Comment by Nerex7** [comment]
How do you mean it is recommended? For what reason exactly? There is no prestige system or am I mistaken?

**Comment by Aegyo** [comment]
There is no prestige system, I just mean that since the game is only in beta, most updates will change the flow of the game and Isha has mentioned previously that you should reset if you want to experience the game as it was intended.
