### ISSUE TITLE
Use project pages

### ISSUE THREAD

**Issue by diff-by-default** [Ishadijcks/Ishadijcks.github.io#12]
I'd be interested in contributing to the pokeclicker project, but having to deal with all of these projects in the same repo seems cumbersome. Pokeclicker should probably be in its own repo with an associated gh-pages branch to mimic the current one.

**Comment by Ishadijcks** [comment]
You are right, done!

**Comment by diff-by-default** [comment]
Cool. I'm not sure if you're familiar with [project pages](https://help.github.com/articles/creating-project-pages-manually/) (as opposed to user pages, which is what you are currently using), so I'll post this here anyway. If you [rename](https://help.github.com/articles/renaming-a-repository/) your repository and create a 'gh-pages' branch, your current github pages link (http://ishadijcks.github.io/PokeClicker/) will still work (assuming you title the repo 'pokeclicker').

Of course, this is completely optional...but a more descriptive repo name seems like a benefit to me.

**Comment by Ishadijcks** [comment]
Cool, I'll look into that. Btw, can you come in the IRC chat for a bit?
