### ISSUE TITLE
Select which type is being used

### ISSUE THREAD

**Issue by Nerex7** [Ishadijcks/Ishadijcks.github.io#133]
I don't exactly know how it is done so far, but it seems like only the "primary" type of the Pokémon is being used for it's attack (or defense for the 'npc' ones on the route). So I came up with a suggestion:
How about choosing between which type is being used for attack? E.g. for a Flying/Normal type you can chose wether you want to attack with the flying type or with the normal type. On first thought this would be annoying to switch arround for like half of the 151 Pokémon, but on second thought it allows more depth to the game, like how to switch my roster to farm e.g. water shards more consistently/efficiently.
For the defense it could just use the double typing like it is used in the game, e.g having double effectiveness and double weakness (e.g. attacking a Steel/Rock type with fighting would not result in a 4x effectiveness like it is used in the game).

Another question is how shards are distributed, do they also go by the "primary" type? Or are they distributed 50/50 if there are 2 types?

Edit: I'm new to github and I saw that this issue could have kind of a suggestion flair, how can I do this?

**Comment by Aegyo** [comment]
In the current version, all pokemon only have 1 type. The next update will update all the pokemon to have both types (if it has a secondary type), the damage will be an average, and shards will be 50/50.

The problem with having defenses be a product of the two types is that some pokemon become incredibly weak after the bonus type damage from shards is taken into account (I was getting around 90k vs some and 30k vs the rest)

**Comment by Aegyo** [comment]
I'm pretty sure only the project creator (and any collaborators that have been added) can choose flairs for issues
