### ISSUE TITLE
'mousedown' vs. 'click' events

### ISSUE THREAD

**Issue by yuhasem** [Ishadijcks/Ishadijcks.github.io#134]
I noticed that this project uses click events for all its inputs. This works pretty good but some elements get redrawn every time the game updates and that will recreate the click event. That means that if some begins to click an element before the redraw and finishes the click after the redraw, the game won't register any click at all. It's usually not noticeable because there's only a small window for it to happen, but if your clicking rapidly (such as on a wild pokemon, or on an item to get a long timer) you can feel some of the clicks get dropped. If you use the mousedown event, it only takes one action so it can't be reset across a redrawing and no actions will get dropped. I don't think every element needs this change (nothing in the underground redraws until there's an action) but I think that there are some places this change should be made.

**Comment by Ishadijcks** [comment]
Yeah I noticed that was happening. Good to know why :)
