### ISSUE TITLE
Shiny capture notification

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#140]
The $.notify style option for shiny captures is currently "succes", which looks like it is probably a typo, and is causing the shiny notification to have no styling at all.

I think the notification should look different to the other ones, just for visibility, so changing it to "success" doesn't really feel like a fix. It looks like you can create custom styles, so the shiny star and some kind of gold text might be good for this notification.

Thoughts?

**Comment by Ishadijcks** [comment]
Yeah, I like the pr you made.
