### ISSUE TITLE
Crate drops

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#142]
Isha, you mentioned a while ago about crates being a resource sink, so I'm making this issue to collect ideas for what could drop from the crates.

I have a couple of ideas already:

- Shard Converter, described [here](https://www.reddit.com/r/PokeClicker/comments/5m0ltc/version_092_dual_types_improved_hatching_and/dc2gqcy/?st=ixlgzezt&sh=6c678d92)

- Silver Bottlecap, single use, +10 to a pokemon's IV

- Gold Bottlecap, single use, max a pokemon's IV

- Shiny Powder, single use, make a pokemon shiny

**Comment by yuhasem** [comment]
Maybe whatever the mining energy refill item could drop from crates. Having it as route drop item seems like it would make it too common (I have over 3000 of every item that can drop from routes).

I don't know what Isha's plans are for the Garden, but maybe rare berries could also be obtained from crates.

**Comment by Ishadijcks** [comment]
Yeah that was the idea.
But I want different kind of crates, but I don't really know what to fill them with :p

Seed crates could contain seeds for the garden
Item crates with the regular items, and mine energies.
Currency crates that can be used for very inefficient resource conversion.

Later:

Pokeball crates.

**Comment by yuhasem** [comment]
For item crates you could add Coupons. A coupon would have a daily deal on it, and you can use it to add it to the underground daily deals. Coupons could be either limited time (they expire at the end of the day, or in x number of days) or limited use (once you use the deal x times, it disappears).

**Comment by Ishadijcks** [comment]
Hey that's interesting!
