### ISSUE TITLE
dungeon problem (unless this was intentional)

### ISSUE THREAD

**Issue by alphem** [Ishadijcks/Ishadijcks.github.io#170]
So every once in a while I will do a dungeon and not be able to enter a room(either from one side or not at all). I don't know why.

**Comment by Ishadijcks** [comment]
Do you have a more specific example?

**Comment by alphem** [comment]
It could be because i'm on a chrome book, but it seems to happen more with chest and boss rooms. it usually happens laterally (meaning i have to go upwards and then down) or one will spawn on a corner (meaning I will not be able to enter that room)
![screenshot 2018-01-25 at 10 57 13 am](https://user-images.githubusercontent.com/35810821/35403931-8adaa3fc-01be-11e8-9ad4-81bd925684e3.png) 
i couldn't enter that chest room( i would have to go up and defeat a few regular rooms before i could go down and enter it)
they just won't be accessible from one or more sides

**Comment by Ishadijcks** [comment]
That's quite odd. The entire system got rewritten in the new version so I think it's no longer a problem
