### ISSUE TITLE
Pokédex

### ISSUE THREAD

**Issue by Halflive9L** [Ishadijcks/Ishadijcks.github.io#171]
Add the detail pages for each pokémon to find out types, stats, locations, ...

**Comment by Ishadijcks** [comment]
![image](https://user-images.githubusercontent.com/9715314/40810133-2cd2d4a0-652d-11e8-9b07-c482739c661a.png)
Something like this?

**Comment by Aegyo** [comment]
Nice sprite

**Comment by Halflive9L** [comment]
Yes exactly like that. Or like as close as possible.

**Comment by Ishadijcks** [comment]
I just realised this is the old repo.

Please open the issue here @Halflive9L 

https://github.com/Ishadijcks/pokeclicker
