### ISSUE TITLE
Issue with javascript loading properly

### ISSUE THREAD

**Issue by Redd500** [Ishadijcks/Ishadijcks.github.io#31]
When I load up the game, the game states that my javascript isn't being loaded properly, nothing works except for basic html functions, and the console states:

pokemonsPerRoute.js:132 Uncaught TypeError: Cannot read property 'land' of undefined(…)

**Comment by Ishadijcks** [comment]
Geez now that is an old one, do you happen to know how old your savefile is?

**Comment by Redd500** [comment]
I think I played a couple updates before the bug appeared which was about 4 to 3 updates ago?

**Comment by Ishadijcks** [comment]
Huh, can you send me your savefile please?

**Comment by Redd500** [comment]
Do I use localStorage.getItem("player") and copy the data here, or do I do something else?

**Comment by Ishadijcks** [comment]
http://imgur.com/QhyYsjR

**Comment by Redd500** [comment]
{"clickAttack":86,"clickMultiplier":6,"attack":3853,"attackMultiplier":1,"money":157697,"moneyMultiplier":2.8,"expMultiplier":1.6000000000000003,"catchBonus":27,"route":72,"pokeballs":-1142,"routeVariation":5,"catchTime":500,"caughtPokemonList":[{"id":99,"name":"Kingler","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":130,"route":10,"health":100,"levelType":"medium fast","experience":104899.59999999999},{"id":98,"name":"Krabby","catchRate":225,"evolution":"Kingler","evoLevel":28,"evolved":1,"type":"water","attack":105,"route":4,"health":100,"levelType":"medium fast","experience":124002.40000000005},{"id":130,"name":"Gyarados","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":125,"route":null,"health":100,"levelType":"slow","experience":113010.39999999998},{"id":85,"name":"Dodrio","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":110,"route":17,"health":100,"levelType":"medium fast","experience":103430.79999999996},{"id":57,"name":"Primeape","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"fighting","attack":105,"route":23,"health":100,"levelType":"medium fast","experience":106016.79999999999},{"id":28,"name":"Sandslash","catchRate":90,"evolution":null,"evoLevel":null,"evolved":0,"type":"ground","attack":100,"route":23,"health":100,"levelType":"medium fast","experience":112148.79999999999},{"id":22,"name":"Fearow","catchRate":90,"evolution":null,"evoLevel":null,"evolved":0,"type":"flying","attack":90,"route":9,"health":100,"levelType":"medium fast","experience":119757.50000000001},{"id":143,"name":"Snorlax","catchRate":25,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":110,"route":16,"health":100,"levelType":"slow","experience":106781.2},{"id":119,"name":"Seaking","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":92,"route":4,"health":100,"levelType":"medium fast","experience":96959.5},{"id":55,"name":"Golduck","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":82,"route":6,"health":100,"levelType":"medium fast","experience":121158.90000000002},{"id":24,"name":"Arbok","catchRate":90,"evolution":null,"evoLevel":null,"evolved":0,"type":"poison","attack":85,"route":23,"health":100,"levelType":"medium fast","experience":111235.59999999999},{"id":67,"name":"Machoke","catchRate":90,"evolution":"Machamp","evoLevel":"Trade","evolved":0,"type":"fighting","attack":100,"route":null,"health":100,"levelType":"medium slow","experience":98970.39999999997},{"id":56,"name":"Mankey","catchRate":190,"evolution":"Primeape","evoLevel":28,"evolved":1,"type":"fighting","attack":80,"route":3,"health":100,"levelType":"medium fast","experience":125107.9000000001},{"id":84,"name":"Doduo","catchRate":190,"evolution":"Dodrio","evoLevel":31,"evolved":1,"type":"normal","attack":85,"route":16,"health":100,"levelType":"medium fast","experience":107723.2},{"id":70,"name":"Weepinbell","catchRate":120,"evolution":"Victreebel","evoLevel":"Leaf Stone","evolved":0,"type":"grass","attack":90,"route":12,"health":100,"levelType":"medium slow","experience":119060.1},{"id":15,"name":"Beedrill","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"bug","attack":80,"route":null,"health":100,"levelType":"medium fast","experience":121158.90000000002},{"id":77,"name":"Ponyta","catchRate":190,"evolution":"Rapidash","evoLevel":40,"evolved":1,"type":"fire","attack":85,"route":17,"health":100,"levelType":"medium fast","experience":105347.19999999997},{"id":20,"name":"Raticate","catchRate":127,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":81,"route":16,"health":100,"levelType":"medium fast","experience":115392.4},{"id":27,"name":"Sandshrew","catchRate":255,"evolution":"Sandslash","evoLevel":22,"evolved":1,"type":"ground","attack":75,"route":3,"health":100,"levelType":"medium fast","experience":124196.00000000007},{"id":78,"name":"Rapidash","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"fire","attack":100,"route":null,"health":100,"levelType":"medium fast","experience":67181.00000000003,"timeStamp":1442775095},{"id":47,"name":"Parasect","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"grass","attack":95,"route":null,"health":100,"levelType":"medium fast","experience":71981.60000000006,"timeStamp":1442774124},{"id":80,"name":"Slowbro","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":75,"route":12,"health":100,"levelType":"medium fast","experience":114001.6},{"id":66,"name":"Machop","catchRate":180,"evolution":"Machoke","evoLevel":28,"evolved":1,"type":"fighting","attack":80,"route":10,"health":100,"levelType":"medium slow","experience":118126.00000000001},{"id":69,"name":"Bellsprout","catchRate":255,"evolution":"Weepinbell","evoLevel":21,"evolved":1,"type":"grass","attack":75,"route":5,"health":100,"levelType":"medium slow","experience":123826.40000000005},{"id":145,"name":"Zapdos","catchRate":3,"evolution":null,"evoLevel":null,"evolved":0,"type":"electric","attack":90,"route":50,"health":100,"levelType":"slow","experience":97137.59999999999},{"id":118,"name":"Goldeen","catchRate":225,"evolution":"Seaking","evoLevel":33,"evolved":1,"type":"water","attack":67,"route":4,"health":100,"levelType":"medium fast","experience":123275.30000000005},{"id":6,"name":"Charizard","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"fire","attack":84,"route":null,"health":100,"levelType":"medium slow","experience":94072.20000000004},{"id":97,"name":"Hypno","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"psychic","attack":73,"route":null,"health":100,"levelType":"medium fast","experience":103365.99999999996},{"id":53,"name":"Persian","catchRate":90,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":70,"route":null,"health":100,"levelType":"medium fast","experience":104360.79999999997},{"id":33,"name":"Nidorino","catchRate":120,"evolution":"Nidoking","evoLevel":"Moon Stone","evolved":0,"type":"poison","attack":72,"route":9,"health":100,"levelType":"medium slow","experience":120374.6},{"id":79,"name":"Slowpoke","catchRate":190,"evolution":"Slowbro","evoLevel":37,"evolved":1,"type":"water","attack":65,"route":10,"health":100,"levelType":"medium fast","experience":118749.90000000001},{"id":83,"name":"Farfetch'd","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":65,"route":12,"health":100,"levelType":"medium fast","experience":118693.80000000002},{"id":49,"name":"Venomoth","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"grass","attack":65,"route":14,"health":100,"levelType":"medium fast","experience":113875.6},{"id":117,"name":"Seadra","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":65,"route":12,"health":100,"levelType":"medium fast","experience":113383.6},{"id":42,"name":"Golbat","catchRate":90,"evolution":null,"evoLevel":null,"evolved":0,"type":"poison","attack":80,"route":null,"health":100,"levelType":"medium fast","experience":73721.80000000006,"timeStamp":1442773757},{"id":18,"name":"Pidgeot","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"flying","attack":80,"route":null,"health":100,"levelType":"medium slow","experience":86141.20000000004,"timeStamp":1442772265},{"id":23,"name":"Ekans","catchRate":255,"evolution":"Arbok","evoLevel":22,"evolved":1,"type":"poison","attack":60,"route":4,"health":100,"levelType":"medium fast","experience":123246.70000000004},{"id":21,"name":"Spearow","catchRate":255,"evolution":"Fearow","evoLevel":20,"evolved":1,"type":"flying","attack":60,"route":3,"health":100,"levelType":"medium fast","experience":124075.00000000007},{"id":146,"name":"Moltres","catchRate":3,"evolution":null,"evoLevel":null,"evolved":0,"type":"fire","attack":100,"route":50,"health":100,"levelType":"slow","experience":62396.400000000016,"timeStamp":1442775345},{"id":58,"name":"Growlithe","catchRate":190,"evolution":"Arcanine","evoLevel":"Fire Stone","evolved":0,"type":"fire","attack":70,"route":7,"health":100,"levelType":"slow","experience":123364.40000000005},{"id":46,"name":"Paras","catchRate":190,"evolution":"Parasect","evoLevel":24,"evolved":1,"type":"grass","attack":70,"route":27,"health":100,"levelType":"medium fast","experience":86257.40000000004,"timeStamp":1442772262},{"id":51,"name":"Dugtrio","catchRate":50,"evolution":null,"evoLevel":null,"evolved":0,"type":"ground","attack":80,"route":null,"health":100,"levelType":"medium fast","experience":66076.40000000001,"timeStamp":1442775223},{"id":61,"name":"Poliwhirl","catchRate":120,"evolution":"Poliwrath","evoLevel":"Water Stone","evolved":0,"type":"water","attack":65,"route":10,"health":100,"levelType":"medium slow","experience":118483.6},{"id":19,"name":"Rattata","catchRate":255,"evolution":"Raticate","evoLevel":20,"evolved":1,"type":"normal","attack":56,"route":1,"health":100,"levelType":"medium fast","experience":125404.40000000007},{"id":44,"name":"Gloom","catchRate":120,"evolution":"Vileplume","evoLevel":"Leaf Stone","evolved":0,"type":"grass","attack":65,"route":12,"health":100,"levelType":"medium slow","experience":113318.79999999999},{"id":5,"name":"Charmeleon","catchRate":45,"evolution":"Charizard","evoLevel":32,"evolved":1,"type":"fire","attack":64,"route":null,"health":100,"levelType":"medium slow","experience":118857.70000000001},{"id":30,"name":"Nidorina","catchRate":120,"evolution":"Nidoqueen","evoLevel":"Moon Stone","evolved":0,"type":"poison","attack":62,"route":9,"health":100,"levelType":"medium slow","experience":120084.2},{"id":90,"name":"Shellder","catchRate":190,"evolution":"Cloyster","evoLevel":"Water Stone","evolved":0,"type":"water","attack":65,"route":6,"health":100,"levelType":"slow","experience":123081.70000000004},{"id":48,"name":"Venonat","catchRate":190,"evolution":"Venomoth","evoLevel":31,"evolved":1,"type":"grass","attack":55,"route":12,"health":100,"levelType":"medium fast","experience":117974.8},{"id":73,"name":"Tentacruel","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":70,"route":19,"health":100,"levelType":"slow","experience":100609.59999999996},{"id":82,"name":"Magneton","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"electric","attack":60,"route":null,"health":100,"levelType":"medium fast","experience":97443.09999999999},{"id":17,"name":"Pidgeotto","catchRate":120,"evolution":"Pidgeot","evoLevel":36,"evolved":1,"type":"flying","attack":60,"route":24,"health":100,"levelType":"medium slow","experience":117253.6},{"id":54,"name":"Psyduck","catchRate":190,"evolution":"Golduck","evoLevel":33,"evolved":1,"type":"water","attack":52,"route":4,"health":100,"levelType":"medium fast","experience":123912.20000000006},{"id":32,"name":"Nidoran♂","catchRate":235,"evolution":"Nidorino","evoLevel":16,"evolved":1,"type":"poison","attack":57,"route":2,"health":100,"levelType":"medium slow","experience":122254.50000000004},{"id":144,"name":"Articuno","catchRate":3,"evolution":null,"evoLevel":null,"evolved":0,"type":"ice","attack":85,"route":50,"health":100,"levelType":"slow","experience":61858.800000000025,"timeStamp":1442775357},{"id":114,"name":"Tangela","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"grass","attack":55,"route":21,"health":100,"levelType":"medium fast","experience":96862},{"id":96,"name":"Drowzee","catchRate":190,"evolution":"Hypno","evoLevel":26,"evolved":1,"type":"psychic","attack":48,"route":11,"health":100,"levelType":"medium fast","experience":119943.4},{"id":39,"name":"Jigglypuff","catchRate":170,"evolution":"Wigglytuff","evoLevel":"Moon Stone","evolved":0,"type":"normal","attack":45,"route":3,"health":100,"levelType":"fast","experience":124153.10000000008},{"id":4,"name":"Charmander","catchRate":45,"evolution":"Charmeleon","evoLevel":16,"evolved":1,"type":"fire","attack":52,"route":100,"health":100,"levelType":"medium slow","experience":125435.40000000007},{"id":132,"name":"Ditto","catchRate":35,"evolution":null,"evoLevel":null,"evolved":0,"type":"normal","attack":48,"route":13,"health":100,"levelType":"medium fast","experience":114653.20000000001},{"id":60,"name":"Poliwag","catchRate":255,"evolution":"Poliwhirl","evoLevel":25,"evolved":1,"type":"water","attack":50,"route":4,"health":100,"levelType":"medium slow","experience":124471.00000000009},{"id":43,"name":"Oddish","catchRate":255,"evolution":"Gloom","evoLevel":21,"evolved":1,"type":"grass","attack":50,"route":5,"health":100,"levelType":"medium slow","experience":123944.10000000005},{"id":87,"name":"Dewgong","catchRate":75,"evolution":null,"evoLevel":null,"evolved":0,"type":"water","attack":70,"route":null,"health":100,"levelType":"medium fast","experience":53202.80000000003,"timeStamp":1442776354},{"id":52,"name":"Meowth","catchRate":255,"evolution":"Persian","evoLevel":28,"evolved":1,"type":"normal","attack":45,"route":5,"health":100,"levelType":"medium fast","experience":123464.50000000006},{"id":50,"name":"Diglett","catchRate":255,"evolution":"Dugtrio","evoLevel":26,"evolved":1,"type":"ground","attack":55,"route":28,"health":100,"levelType":"medium fast","experience":82749.00000000004,"timeStamp":1442772374},{"id":25,"name":"Pikachu","catchRate":190,"evolution":"Raichu","evoLevel":"Thunder Stone","evolved":0,"type":"electric","attack":55,"route":25,"health":100,"levelType":"medium fast","experience":82481.60000000003,"timeStamp":1442772382},{"id":12,"name":"Butterfree","catchRate":45,"evolution":null,"evoLevel":null,"evolved":0,"type":"bug","attack":45,"route":null,"health":100,"levelType":"medium fast","experience":121296.40000000002},{"id":101,"name":"Electrode","catchRate":60,"evolution":null,"evoLevel":null,"evolved":0,"type":"electric","attack":50,"route":null,"health":100,"levelType":"medium fast","experience":96677.40000000001},{"id":29,"name":"Nidoran♀","catchRate":235,"evolution":"Nidorina","evoLevel":16,"evolved":1,"type":"poison","attack":47,"route":2,"health":100,"levelType":"medium slow","experience":125213.40000000008},{"id":16,"name":"Pidgey","catchRate":255,"evolution":"Pidgeotto","evoLevel":18,"evolved":1,"type":"flying","attack":45,"route":1,"health":100,"levelType":"medium slow","experience":125435.40000000007},{"id":37,"name":"Vulpix","catchRate":190,"evolution":"Ninetales","evoLevel":"Fire Stone","evolved":0,"type":"fire","attack":41,"route":7,"health":100,"levelType":"medium fast","experience":121040.10000000002},{"id":35,"name":"Clefairy","catchRate":150,"evolution":"Clefable","evoLevel":"Moon Stone","evolved":0,"type":"normal","attack":45,"route":25,"health":100,"levelType":"fast","experience":85115.00000000003,"timeStamp":1442772305},{"id":116,"name":"Horsea","catchRate":225,"evolution":"Seadra","evoLevel":32,"evolved":1,"type":"water","attack":40,"route":10,"health":100,"levelType":"medium fast","experience":118178.8},{"id":41,"name":"Zubat","catchRate":2550,"evolution":"Golbat","evoLevel":22,"evolved":1,"type":"poison","attack":45,"route":26,"health":100,"levelType":"medium fast","experience":85747.80000000003,"timeStamp":1442772279},{"id":86,"name":"Seel","catchRate":190,"evolution":"Dewgong","evoLevel":34,"evolved":1,"type":"water","attack":45,"route":30,"health":100,"levelType":"medium fast","experience":81155.80000000003,"timeStamp":1442772437},{"id":13,"name":"Weedle","catchRate":255,"evolution":"Kakuna","evoLevel":7,"evolved":1,"type":"bug","attack":35,"route":2,"health":100,"levelType":"medium fast","experience":125236.40000000008},{"id":81,"name":"Magnemite","catchRate":190,"evolution":"Magneton","evoLevel":30,"evolved":1,"type":"electric","attack":35,"route":10,"health":100,"levelType":"medium fast","experience":119302.1},{"id":120,"name":"Staryu","catchRate":225,"evolution":"Starmie","evoLevel":"Water Stone","evolved":0,"type":"water","attack":45,"route":19,"health":100,"levelType":"slow","experience":100441.59999999996},{"id":72,"name":"Tentacool","catchRate":190,"evolution":"Tentacruel","evoLevel":30,"evolved":1,"type":"water","attack":40,"route":11,"health":100,"levelType":"slow","experience":119249.3},{"id":64,"name":"Kadabra","catchRate":100,"evolution":"Alakazam","evoLevel":"Trade","evolved":0,"type":"psychic","attack":35,"route":8,"health":100,"levelType":"medium slow","experience":123162.00000000004},{"id":10,"name":"Caterpie","catchRate":255,"evolution":"Metapod","evoLevel":7,"evolved":1,"type":"bug","attack":30,"route":2,"health":100,"levelType":"medium fast","experience":125349.40000000008},{"id":100,"name":"Voltorb","catchRate":190,"evolution":"Electrode","evoLevel":30,"evolved":1,"type":"electric","attack":30,"route":10,"health":100,"levelType":"medium fast","experience":118537.6},{"id":14,"name":"Kakuna","catchRate":120,"evolution":"Beedrill","evoLevel":10,"evolved":1,"type":"bug","attack":25,"route":24,"health":100,"levelType":"medium fast","experience":123859.40000000005},{"id":11,"name":"Metapod","catchRate":120,"evolution":"Butterfree","evoLevel":10,"evolved":1,"type":"bug","attack":20,"route":24,"health":100,"levelType":"medium fast","experience":123980.40000000005},{"id":63,"name":"Abra","catchRate":200,"evolution":"Kadabra","evoLevel":16,"evolved":1,"type":"psychic","attack":20,"route":5,"health":100,"levelType":"medium slow","experience":123726.30000000006},{"id":129,"name":"Magikarp","catchRate":255,"evolution":"Gyarados","evoLevel":20,"evolved":1,"type":"water","attack":10,"route":4,"health":100,"levelType":"slow","experience":123013.50000000004}],"routeKills":[0,5,69,14,32,120,8,10,22,11,6,7,23,15,59,52,36,55,10,19,13,30,8,8,8,6,43,28,5,5,7,12,5,82,6,5,6,6,6,6,6,5,5,5,6,5,5,5,5,5,10,5,52,157,5,8,5,6,5,5,5,5,5,5,5,5,8,5,6,5,5,5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"starter":"Charmander","upgradeList":[{"id":0,"name":"Pokeball upgrade I","cost":1000,"type":"catchBonus","amount":3,"bought":1,"require":0,"flavorText":"New technology gives you a 3% bonus to catch rate"},{"id":1,"name":"Pokeball upgrade II","cost":5000,"type":"catchBonus","amount":3,"bought":1,"require":3,"flavorText":"New technology gives you a 3% bonus to catch rate"},{"id":2,"name":"Pokeball upgrade III","cost":10000,"type":"catchBonus","amount":3,"bought":1,"require":5,"flavorText":"New technology gives you a 3% bonus to catch rate"},{"id":3,"name":"Pokeball upgrade IV","cost":25000,"type":"catchBonus","amount":3,"bought":1,"require":7,"flavorText":"New technology gives you a 3% bonus to catch rate"},{"id":4,"name":"Pokeball upgrade V","cost":75000,"type":"catchBonus","amount":10,"bought":1,"require":10,"flavorText":"New technology gives you a 10% bonus to catch rate"},{"id":5,"name":"Experience upgrade I","cost":500,"type":"expMultiplier","amount":0.1,"bought":1,"require":0,"flavorText":"New technology gives you a 10% bonus to experience gain"},{"id":6,"name":"Experience upgrade II","cost":5000,"type":"expMultiplier","amount":0.1,"bought":1,"require":1,"flavorText":"New technology gives you a 10% bonus to experience gain"},{"id":7,"name":"Experience upgrade III","cost":50000,"type":"expMultiplier","amount":0.1,"bought":1,"require":4,"flavorText":"New technology gives you a 10% bonus to experience gain"},{"id":8,"name":"Experience upgrade IV","cost":100000,"type":"expMultiplier","amount":0.1,"bought":1,"require":6,"flavorText":"New technology gives you a 10% bonus to experience gain"},{"id":9,"name":"Experience upgrade V","cost":500000,"type":"expMultiplier","amount":0.2,"bought":1,"require":12,"flavorText":"New technology gives you a 20% bonus to experience gain"},{"id":10,"name":"Catch time upgrade I","cost":2000,"type":"catchTime","amount":250,"bought":1,"require":0,"flavorText":"Decrease the catch time by 250 milliseconds"},{"id":11,"name":"Catch time upgrade II","cost":10000,"type":"catchTime","amount":250,"bought":1,"require":2,"flavorText":"Decrease the catch time by 250 milliseconds"},{"id":12,"name":"Catch time upgrade III","cost":25000,"type":"catchTime","amount":500,"bought":1,"require":5,"flavorText":"Decrease the catch time by half a second"},{"id":13,"name":"Catch time upgrade IV","cost":75000,"type":"catchTime","amount":500,"bought":1,"require":8,"flavorText":"Decrease the catch time by half a second"},{"id":14,"name":"Catch time upgrade V","cost":1000000,"type":"catchTime","amount":1000,"bought":1,"require":15,"flavorText":"Decrease the catch time by a whole second"},{"id":15,"name":"Money multiplier upgrade I","cost":1500,"type":"moneyMultiplier","amount":0.25,"bought":1,"require":0,"flavorText":"Gain 25% more money"},{"id":16,"name":"Money multiplier upgrade II","cost":4000,"type":"moneyMultiplier","amount":0.3,"bought":1,"require":3,"flavorText":"Gain 30% more money"},{"id":17,"name":"Money multiplier upgrade III","cost":10000,"type":"moneyMultiplier","amount":0.35,"bought":1,"require":6,"flavorText":"Gain 35% more money"},{"id":18,"name":"Money multiplier upgrade IV","cost":25000,"type":"moneyMultiplier","amount":0.4,"bought":1,"require":10,"flavorText":"Gain 40% more money"},{"id":19,"name":"Money multiplier upgrade V","cost":50000,"type":"moneyMultiplier","amount":0.5,"bought":1,"require":16,"flavorText":"Gain 50% more money"},{"id":20,"name":"Click multiplier upgrade I","cost":100,"type":"clickMultiplier","amount":1,"bought":1,"require":0,"flavorText":"Clicks do 100% more damage"},{"id":21,"name":"Click multiplier upgrade II","cost":500,"type":"clickMultiplier","amount":1,"bought":1,"require":2,"flavorText":"Clicks do 100% more damage"},{"id":22,"name":"Click multiplier upgrade III","cost":1000,"type":"clickMultiplier","amount":1,"bought":1,"require":5,"flavorText":"Clicks do 100% more damage"},{"id":23,"name":"Click multiplier upgrade IV","cost":2500,"type":"clickMultiplier","amount":1,"bought":1,"require":7,"flavorText":"Clicks do 100% more damage"},{"id":24,"name":"Click multiplier upgrade V","cost":5000,"type":"clickMultiplier","amount":1,"bought":1,"require":10,"flavorText":"Clicks do 100% more damage"}],"gymBadges":0,"version":"0.1"}

**Comment by Ishadijcks** [comment]
Version 0.1! bru :p

**Comment by Ishadijcks** [comment]
In Version 0.1 you could go to routes bigger than 25, in your savefile you were on route 72.
When loading the save, it now caps your route at 25. :)

**Comment by Redd500** [comment]
I know I played a version with the map where I was on a much lower route lol.  I don't know what happened.  Also is it fixed now in the playable version?
