### ISSUE TITLE
Fossils giving diamonds when used

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#35]
The way you are handling the default parameter for value and valueType will assign your default value for any falsey parameter passed to it, so it is overwriting 0 when adding the fossils.

http://stackoverflow.com/questions/894860/set-a-default-parameter-value-for-a-javascript-function

**Comment by Ishadijcks** [comment]
Ah, they have a value of 0 but because I OR with 1, it is still assigned 1?

**Comment by Aegyo** [comment]
Yes, that is what is happening for the fossils.

**Comment by Ishadijcks** [comment]
Nice one :)
