### ISSUE TITLE
Professor Oak can explain stuff again

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#42]
It would be neat if there was a way to reread all professor Oak notifications in Pallet Town as a sort of tutorial.

Oak could have a button just like mom. When you click on him it opens a modal with all sorts of buttons.
Each button triggers a function like the one in Oak.js:

var oakExplainDungeonAgain = function(){
	player.dungeonExplain = 0;
	oakExplainDungeons();
}

**Comment by KryptoCrash** [comment]
Hi
