### ISSUE TITLE
While breeding, the check for shinies is when you hatch them.

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#54]
Now the player can select one Oak item, and switch to the shiny charm when he's gonna hatch.

I want to prevent this. So I thought about picking a random number for each egg (below the amount of steps). When progress is there it generates if it should be shiny.

I'm not sure it's the best solution, but it works.

Thoughts?

**Comment by Aegyo** [comment]
What if you also keep track of how much progress is gained while shiny charm is active, and then use that to modify the shiny chance somewhere between 1/1024 and 1/512 ?

**Comment by Ishadijcks** [comment]
Huh that's a good idea

**Comment by XSoldierAntX** [comment]
I know I'm gonna probably sound stupid, or it may not easily fix the problem (not good with JS) but cant you just create rand number, test for < xpokemon.steps, then if it isnt generate a new number, and if it is assign that number to a var or something that the steps check for everytime and then it is decided once the steps are at or above the generated number? Also, Aegyo I like your idea, but honestly I think fixing the 'bug' should be the main concern, and then implementing a shiny charm buff is secondary, but thats just my way of looking at it. (Cause ou can always idle with the shiny charm on if we the current way is changed to hope you get it)

**Comment by Aegyo** [comment]
If you just check at a random point along the progress, there could be a chance that if you deactivate the shiny briefly you will miss the check, making all the time you spent with the charm on pointless. The method I suggested gives credit for the time you had the charm active, and is a decrease to the chance unless the charm was active for the full duration (at which point it becomes equally effective to what it is doing now).

**Comment by XSoldierAntX** [comment]
I see what your saying, I was just partially suggesting that it gets 'fixed' and then add in the shiny charm increasing chance the longer it stays on.
