### ISSUE TITLE
Dual typing

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#55]
Implement dual typing.

This sucks because it's a lot of work.
You can change the type in the pokemonList to an array, or add a type2, not sure what's better.

Enemies can become both types, or a random one.

You could get 2 shards per Pokémon or the random picked one.

**Comment by gro-te** [comment]
I believe this is fixed in #57

**Comment by Ishadijcks** [comment]
Yep, I have merged it to a stage branch. It's kind of a big change so I want to test it a bit more.
