### ISSUE TITLE
Underground square highlight not showing up

### ISSUE THREAD

**Issue by XSoldierAntX** [Ishadijcks/Ishadijcks.github.io#56]
When I hover over any treasure in the dig tab of the underground, the border around the square goes disappears.

**Comment by Ishadijcks** [comment]
This is a bug and not a bug at the same time.

The square is to highlight where you are going to mine. You are not going to mine treasures, so why should the square show up there?

**Comment by XSoldierAntX** [comment]
Like if I was clearing off a plate, and I wanted to hammer on one of 2 spots, but I only wanted to hammer on one of the spots, it would be helpful to know which one im selecting. I understand there are easy ways to work around it, but it would just be a quality of life update at this point.

**Comment by gro-te** [comment]
I can see the use for some people. I do however think it doesn't look nearly as good.
