### ISSUE TITLE
I need help with animations for the Safari Zone

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#59]
If you check out the safari branch, you'll notice that I've made tons of progress on the Safari Zone.

The movement feels kind of weird though, and I have no idea how to fix it. This issue is kinda vague, sorry 👍

**Comment by Halflive9L** [comment]
It looks pretty good though.

**Comment by Aegyo** [comment]
This was never marked as fixed after I improved it

**Comment by Ishadijcks** [comment]
Yep thanks :)
