### ISSUE TITLE
New quests! (Post quest suggestions here)

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#69]
Dig x items in the underground.
Clear x layers in the underground.

Use the Chisel x times in the underground.
Use the Hammer x times in the underground.

Use daily deals 1 time.

**Comment by Dimava** [comment]
(`calculated value`)
- Kill `some`  `wild pokemon`s
- Catch `some` `wild pokemon`s
- Get `some` `item`s from wild pokemons
- Dig `some` items in mining
- Get `some` evolution stones
