### ISSUE TITLE
Gym battles don't count towards egg hatching.

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#70]
Each gym has a variable called badgeReq, the number of badges required to start that gym.
It is a nice indication of how much steps it should give.

The routes give 1 (route 1) - 5 (route 25) steps.

The gyms could give floor(badgeReq/3) + 1 steps. I think that's fair.

Thoughts?

**Comment by XSoldierAntX** [comment]
It doesn't make sense logically, but it would be fair. Logically you aren't walking around trying to get these fights with the pokemon, you're standing there fighting them as they are thrown out. That's just my opinion though.

**Comment by Ishadijcks** [comment]
Yeah it kinda clashes with the 'walking around' idea, I guess it feels weird if it counts, and if it doesn't count.

**Comment by Aegyo** [comment]
I would suggest making gyms slightly better for egg progress than nearby routes, since gyms require active play currently. My suggestion for the formula is floor(sqrt(badgeReq*3 + 1)). This will give:
1. at Pewter
2. at Cerulean
3. at Celadon
4. at Fuschia
5. at Viridian
6. at Champion

**Comment by Ishadijcks** [comment]
Agreed.

**Comment by Ishadijcks** [comment]
Implemented.
