### ISSUE TITLE
[Discussion] More random features that are the same for everyone

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#71]
So far I really like the daily deals, and I've been thinking about more features that could be randomised, but still the same for everyone.

One thing that came to mind is an event system.
Based on the current date, an event is generated.
Events are small stuff like 10% more money or 30% more exp from dungeons.

These features give people something to look forward to.
Share your ideas :)

**Comment by XSoldierAntX** [comment]
Its a pretty cool idea, personally I like it. People really complain about the lack of features/things to do, so this might keep people happy a little longer.

**Comment by Aegyo** [comment]
I mentioned a while ago the idea of pokemon swarms, not sure if you forgot about it or just decided it wasn't worth implementing.

**Comment by Ishadijcks** [comment]
Sorry, what was the idea exactly?

**Comment by Aegyo** [comment]
Each day a pokemon is chosen (preferably from a list of rare ones, ie dungeon only pokemon) to appear with a high chance on some route number.

**Comment by Aegyo** [comment]
I made a swarm thing.
https://rawgit.com/Aegyo/Ishadijcks.github.io/swarms/index.html

Upcoming swarms:
https://docs.google.com/spreadsheets/d/1-Dyqz0uWqgB079GShDf9ru5BfYKc61gusy0lYyhzFgs/edit#gid=1153055044

Only non-route pokemon can swarm (except legendaries) and the encounter rate is currently 50%
Swarm route occasionally flashes purple (chance of this will be reduced by a lot, at 10% for testing), and also oak will tell you which route pokemon are swarming at.

Water pokemon should only swarm on route 19, 20 or 21, other pokemon only land routes. Also, it currently doesn't stop unavailable pokemon from swarming (ie pinsir, scyther), should I add them to the list of pokemon to ignore?

**Comment by Aegyo** [comment]
Similar to the loot crate thing, but there could be some kind of lottery system where you can buy as many tickets as you like, and then the next time you load the game on a new day your tickets are checked how many matches you have with the lottery number for the day after you bought them (could do it as once prize draw per week).

Prizes can range from common items to rare (same pool as loot crates probably) based on how many matches you get. Maybe also have more expensive tickets which have guaranteed matches, but have a worse (chance of winning jackpot)/cost ratio.

Similarly, a daily lottery based on player ID can be added, as in the department stores of the main games.

The "same for everyone" thing comes in by making the winning lottery numbers based on the date, if that wasn't clear.

Lottery numbers can be replaced with the pokemon of that pokedex number.
