### ISSUE TITLE
[Discussion] Statistics!

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#73]
Everybody loves statistics.

I'm working on a cool statistics page, and I was wondering what kind of stats would be interesting to track.
Think of stuff like total money and gyms defeated.

Discuss!

**Comment by XSoldierAntX** [comment]
Total Money. I wonder who had that idea xD Total Shinies ever gotten, Total QP, Dungeon Tokens.

**Comment by Aegyo** [comment]
Shinies hatched
