### ISSUE TITLE
Embedded chat

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#74]
It would be neat if the chat was embedded in the game.
The only problem is where?

Of course it should also be toggle able, in case players don't want to play with a chat next to the game.

Embedding the Kiwi IRC in an iframe looks pretty good.

**Comment by Aegyo** [comment]
Maybe some element at the side, slightly sticking out, which slides into view on hover, slides back when your mouse leaves the element.

Some css to make it clear when there is a new message.

**Comment by Ishadijcks** [comment]
Is that convenient enough?

I like how it is on Kongregate with the chat to the right of the game.

**Comment by Aegyo** [comment]
I'm just thinking that people playing on smaller screens probably don't have the space, so they would be hiding the window constantly when going back to the game.

**Comment by XSoldierAntX** [comment]
Hes referring to people like me. No, having it like Kongregate.wouldnt work because my screen is small as it is.

**Comment by Ishadijcks** [comment]
Yep,

I'm probably gonna remove the stats table anyway. Make it a new tab in a modal somewhere.

**Comment by Halflive9L** [comment]
@Ishadijcks  Perhaps a slide frame on the right or left. Then you can hide, access it whenever you want.

**Comment by Ishadijcks** [comment]
Yeah that's a good idea. Can you look into that? :)

**Comment by Dimava** [comment]
https://jsfiddle.net/j9prut3k/2/ 
https://jsfiddle.net/j9prut3k/2/embedded/result/

**Comment by Ishadijcks** [comment]
Cool cool
