### ISSUE TITLE
Mining Energy refills

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#75]
Obtainable item.
It gives you back all your mining energy.

**Comment by gro-te** [comment]
What did you have in mind for the item?

**Comment by yuhasem** [comment]
What if you repurpose ethers to be energy giving items? Then you could have it so regular ethers give a flat amount (say 25?) while max ethers give 100% energy back. Ethers could also be used to restore energy for safari and other extensions instead of just mining.

**Comment by Ishadijcks** [comment]
That's a good idea, more in the Pokémon theme.
