### ISSUE TITLE
Fancy animations instead of a boring console

### ISSUE THREAD

**Issue by Ishadijcks** [Ishadijcks/Ishadijcks.github.io#76]
As it is right now, the console is not really read. The messages go too fast, and most of the messages aren't interesting.

This could be fixed by adding animations to the current enemy box. For example if you defeat a Pokémon, a coin falls from it, or a shard, or dungeon tokens. This looks good, and could free up some space at the bottom.

**Comment by Dimava** [comment]
Writing this

**Comment by Ishadijcks** [comment]
Awesome!

**Comment by Dimava** [comment]
#97
