### ISSUE TITLE
Pokemon variation

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#78]
The main games have IVs for pokemon which make their stats different, introducing variety into the pokemon people have. It would be a nice addition to have this for the attack stat on our pokemon.

I'm not sure how the IV of evolution pokemon would be determined, either the same as the pokemon evolving from it, or randomly decided on evolution (and when being hatched)

If you catch a pokemon with a better IV, it should replace the one you have currently.

This would add an extra thing for players to grind for in end game, and give players something else to compare with each other.

**Comment by Aegyo** [comment]
Breeding should never decrease the IV, in fact breeding could be used as a way to gradually increase the IV for your pokemon, the formula should have a diminishing chance to increase to higher numbers. My suggestion is newIV = oldIV + floor( pow( rand, 3.5 ) \* ( 32 - oldIV ) )

**Comment by Aegyo** [comment]
This would introduce an issue, shiny pokemon will essentially be stuck at the IV you get them. Would need to introduce a way to breed shiny pokemon, perhaps add a "Shiny Incubator" - you can breed 1 shiny pokemon at a time, only pokemon you already have shiny can produce an egg for this and it is guaranteed to hatch shiny.

Also, when you catch a shiny pokemon for the first time should it have a new IV, or take the IV of the non shiny version that it will replace?

I have run some numbers for the formula and a power of 3.5 translates to about 170 eggs to take a 0 IV pokemon up to 31, so around 1/3 of the expected number of eggs to get a shiny. Is this a reasonable number?

**Comment by Aegyo** [comment]
Perhaps the number of Shiny Incubators you have available should depend on the number of unique shiny pokemon you have, the first unlocking on your first shiny, second at 25% of unique shinies etc

**Comment by Ishadijcks** [comment]
Very interesting ideas, but for somewhere in the future :)
