### ISSUE TITLE
Egg Hatching Quests

### ISSUE THREAD

**Issue by XSoldierAntX** [Ishadijcks/Ishadijcks.github.io#81]
I don't think anyone has had this issue yet, and after some point it isnt an issue anymore, but what happens when someone has all the shinies or nearly all, but they want to try and break their record or something, so they can't breed anymore. I suggest checking the shiny count when creating quests and if it isnt under x amount it cant be a hatching quest.

**Comment by Ishadijcks** [comment]
You can still get eggs from shops.
