### ISSUE TITLE
Egg Steps

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#86]
Currently almost all pokemon take the default number of steps (500), this should be changed to how many steps each pokemon would take in the main games.

The number of steps may need to be scaled from the exact value from the main games, if so which pokemon would be best to use as a reference for the scale?

[List of all pokemon with their steps](http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_base_Egg_cycles)

**Comment by Ishadijcks** [comment]
Hmm, so for the gen 1 Pokémon.

It ranges from 5 (magikarp) to 120 (mew-two).
The median seems to be 20? So that could be the current 500?

**Comment by Aegyo** [comment]
That sounds reasonable to me

**Comment by Ishadijcks** [comment]
Hmm, I ran the numbers and it seems a bit low.

https://docs.google.com/spreadsheets/d/1eMn2mkcwf1_akyNgYxHC6EIfGsKW8NHDLcLAE-L7tQs/edit#gid=0
