### ISSUE TITLE
Paras's dual typing is Bug/Grass

### ISSUE THREAD

**Issue by Aegyo** [Ishadijcks/Ishadijcks.github.io#92]
For random eggs, Paras is currently an option for the grass egg, but 
it's primary type is bug. I'm not sure whether you want to pick a different grass pokemon to replace paras or just switch the types around. The replacement options are Exeggcute (which will likely be a safari only pokemon) or Tangela.

**Comment by Ishadijcks** [comment]
Changed to Tangela, thanks :)
