### ISSUE TITLE
Minor quality improvements

### ISSUE THREAD

**Issue by Dimava** [Ishadijcks/Ishadijcks.github.io#93]
- [x]  Remove `margin-bottom` from `#itemTable`
- [x]  Remove `height: 320px;` from `#statDiv`
- [x]  Add backgroung for shinies
- [x]  Decrease size of `Amount` header in `#itemTable` (replace with `Amt` or change font)
- [x]  Show quest modal on quest bar click when not completed
- [x]  Pointer cursor for `Use` buttons, help cursor for `tooltip item`s
- [x] Move `Math.floor` from `egg exp gain` to `egg exp display` ( #108 )
- [x] Move `Catch chance: xx%` display inside `setTimeout` to prevent bar jumps
- [x] Use `pokedexBonusExp` in `gainExp` formula (#107)
- [x] Hide empty `#upgradeBox`

**Comment by Dimava** [comment]
- Quest revard optimisation (shiny is too small)

**Comment by Dimava** [comment]
- Move `Math.floor` from `egg exp gain` to `egg exp display`

**Comment by Aegyo** [comment]
Moving math.floor for eggs will solve #108 right?

**Comment by Dimava** [comment]
Yes

**Comment by Aegyo** [comment]
Considering the health of gym pokemon, and the buff to egg progress this will bring to many routes, it may be more balanced to change the gym egg progress formula to sqrt((badgeReq \* **4**) + 1)

**Comment by Dimava** [comment]
- [ ] Use `pokedexBonusExp` in `gainExp` formula

**Comment by Dimava** [comment]
Quest revard optimisation (shiny is too small) moved to #112

**Comment by Dimava** [comment]
**Completed** #111
